name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    name: Run shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v4

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.19

  test:
    name: Test setup-postgresql
    runs-on: ${{ matrix.platform }}
    concurrency: ${{ matrix.platform }}-${{ matrix.postgresql_version }}-${{ github.ref }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        postgresql_version: [11, 12, 14, 15, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run setup-postgresql
        uses: ./
        with:
          postgresql-version: ${{ matrix.postgresql_version }}
      - name: Verify PostgreSQL
        run: |
      - name: Verify PostgreSQL
        run: |
          pg_dump --version | grep -q "PostgreSQL ${matrix.postgresql_version}.*" # Check if the version in the output matches the version in the matrix
          psql --version | grep -q "psql (PostgreSQL) ${matrix.postgresql_version}.*" # Check if the version in the output matches the version in the matrix
          pg_restore --version | grep -q "pg_restore (PostgreSQL) ${matrix.postgresql_version}.*" # Check if the version in the output matches the version in the matrix
